import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Chatbot from "@/components/Chatbot";
import Link from "next/link";
import { ModeToggle } from "@/components/mode-toggle";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geistSans.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="min-h-screen bg-background">
            <nav className="border-b bg-card">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-16">
                  <div className="flex items-center space-x-8">
                    <Link href="/" className="text-xl font-semibold">
                      CyberHype
                    </Link>
                    <div className="hidden md:flex items-center space-x-4">
                      <Link href="/" className="nav-link">Home</Link>
                    </div>
                  </div>
                  <div className="flex items-center space-x-4">
                    <ModeToggle />
                    <Link 
                      href="/logout"
                      className="px-4 py-2 rounded-md bg-destructive text-destructive-foreground hover:bg-destructive/90"
                    >
                      Logout
                    </Link>
                  </div>
                </div>
              </div>
            </nav>
            
            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
              {children}
            </main>
          </div>
          <Chatbot />
          <Toaster position="top-right" richColors />
        </ThemeProvider>
      </body>
    </html>
  )
}

export default Layout;
